// Mock data: Módulo Gestão Contratual / Projeto Boaventura
const GROUPS = {
  engenharia:  { id: 'engenharia',  label: 'Engenharia',   email: 'engenharia@hc2.pb',  icon: 'HardHat',      tone: 'green' },
  producao:    { id: 'producao',    label: 'Produção',     email: 'producao@hc2.pb',    icon: 'Package',      tone: 'violet' },
  suprimentos: { id: 'suprimentos', label: 'Suprimentos',  email: 'suprimentos@hc2.pb', icon: 'ShoppingBag',  tone: 'blue' },
  qualidade:   { id: 'qualidade',   label: 'Qualidade',    email: 'qualidade@hc2.pb',   icon: 'FlaskConical', tone: 'cyan' },
  contraparte: { id: 'contraparte', label: 'Contraparte (Petrobras)', email: 'gestao.contrato@petrobras.com.br', icon: 'Building2', tone: 'slate' },
  meus:        { id: 'meus',        label: 'Criados por mim', email: 'iniciado pela equipe', icon: 'User',        tone: 'blue' },
};

const PARECERES = [
  {
    id: 'p1',
    criticality: 'critical',
    subject: 'Solicitação de revisão do escopo do skid de filtragem 4730-IF-001',
    sender: 'eng.proj@parceiroengenharia.com.br',
    senderName: 'Eng. Projeto: Parceiro',
    date: '11/05/2026 09:14',
    group: 'engenharia',
    summary: 'Contraparte solicita inclusão de duas linhas adicionais ao skid 4730-IF-001 e teste integrado em campo. A solicitação não consta na Lista Mestra de Documentos da Revisão E e não há registro em ata de reunião técnica.',
    justification: 'Classificado como crítico porque (i) altera escopo de fornecimento previsto na Cláusula 4.2 do contrato; (ii) o pedido vem por e-mail informal, sem TAP nem RFI registrado; (iii) prazo solicitado (15 dias) é incompatível com o caminho crítico do comissionamento da Unidade B.',
    references: ['Cláusula 4.2: Escopo de fornecimento', 'Anexo III: LMD Rev. E', 'Memorial descritivo IF-001'],
    starred: true,
    status: 'em_analise',
    pathRisk: 'critical',
  },
  {
    id: 'p2',
    criticality: 'critical',
    subject: 'Atraso na liberação de FCD da malha de instrumentação V-128',
    sender: 'plan.boaventura@hc2.com.br',
    senderName: 'Planejamento: HC²',
    date: '10/05/2026 08:42',
    group: 'engenharia',
    summary: 'Planejamento informa atraso de 11 dias úteis na liberação do FCD para malha V-128 por pendências de réplica/tréplica não resolvidas. O atraso impacta diretamente o início do TTAS programado para 22/05.',
    justification: 'Classificado como crítico porque a Cláusula 6.1 estabelece marco contratual em 22/05 para início do TTAS da Unidade B. O caminho crítico atual aponta esta atividade como predecessora obrigatória de mais 4 marcos.',
    references: ['Cláusula 6.1: Marcos contratuais', 'Cronograma físico baseline'],
    starred: true,
    status: 'em_analise',
    pathRisk: 'critical',
  },
  {
    id: 'p3',
    criticality: 'informative',
    subject: 'Réplica nº 134 emitida: Memorial descritivo SOP-4730-001',
    sender: 'controle.docs@hc2.com.br',
    senderName: 'Controle Documental: HC²',
    date: '06/05/2026 17:30',
    group: 'engenharia',
    summary: 'Réplica nº 134 emitida pela contraparte com 6 comentários no memorial descritivo SOP-4730-001 Rev. C. Comentários são de natureza editorial e não impactam escopo técnico.',
    justification: 'Classificado como informativo porque os apontamentos são editoriais (formatação, numeração de figuras) e não tangenciam cláusulas técnicas ou prazos contratuais.',
    references: ['SOP-4730-001 Rev. C'],
    starred: true,
    status: 'concluida',
  },
  {
    id: 'p4',
    criticality: 'critical',
    subject: 'Não conformidade NC-2026-047: vazamento em teste hidrostático',
    sender: 'qa.boaventura@hc2.com.br',
    senderName: 'Qualidade: HC²',
    date: '06/05/2026 14:22',
    group: 'qualidade',
    summary: 'NC-2026-047 aberta após teste hidrostático na linha 10"-V128-4730-1387-RWP02(ZUT)-IQ. Vazamento em junta soldada exige retesteamento e novo dossiê de qualidade da malha.',
    justification: 'Classificado como crítico porque o retrabalho impacta marco contratual de TTAS (Cláusula 6.1) e enseja registro formal de evento que pode caracterizar mudança de prazo conforme Cláusula 9.3: Eventos de força maior e equivalentes.',
    references: ['NC-2026-047', 'Cláusula 6.1', 'Cláusula 9.3'],
    starred: false,
    status: 'aguardando',
    pathRisk: 'preventive',
  },
  {
    id: 'p5',
    criticality: 'informative',
    subject: 'Confirmação de recebimento: Dossiê de qualidade DQ-128',
    sender: 'qa.contraparte@petrobras.com.br',
    senderName: 'Qualidade: Petrobras',
    date: '06/05/2026 11:05',
    group: 'qualidade',
    summary: 'Contraparte confirmou recebimento do DQ-128 sem ressalvas. Início do prazo de análise técnica (10 dias úteis conforme Cláusula 7.4).',
    justification: 'Classificado como informativo porque é registro de marco previsto. Sem necessidade de ação imediata: acompanhamento automático do prazo.',
    references: ['Cláusula 7.4: Prazos de análise'],
    starred: false,
    status: 'aguardando',
  },
  {
    id: 'p6',
    criticality: 'critical',
    subject: 'Atraso na entrega de válvulas KS-204: fornecedor Tecnoval',
    sender: 'compras@hc2.com.br',
    senderName: 'Suprimentos: HC²',
    date: '05/05/2026 16:48',
    group: 'suprimentos',
    summary: 'Tecnoval comunica atraso de 22 dias na entrega das válvulas KS-204 destinadas à malha V-128. Justificativa: indisponibilidade de matéria-prima homologada API 6D.',
    justification: 'Classificado como crítico porque o atraso de 22 dias supera a folga prevista no cronograma (8 dias). Impacto direto no marco de TTAS-Unidade B e potencial gatilho de Cláusula 9.2: Atrasos imputáveis a terceiros.',
    references: ['Cláusula 9.2', 'Cronograma: folga V-128'],
    starred: true,
    status: 'notificada',
    pathRisk: 'preventive',
  },
  {
    id: 'p7',
    criticality: 'informative',
    subject: 'Pedido de cotação: substituição de gaxetas KS-204',
    sender: 'compras@hc2.com.br',
    senderName: 'Suprimentos: HC²',
    date: '05/05/2026 10:12',
    group: 'suprimentos',
    summary: 'Solicitação de cotação para substituição de gaxetas das válvulas KS-204 dentro do escopo já contratado. Sem alteração de valor agregado.',
    justification: 'Classificado como informativo porque a substituição está prevista no Anexo II: Lista de itens de reposição e não altera valores ou prazos.',
    references: ['Anexo II'],
    starred: false,
    status: 'aguardando',
  },
  {
    id: 'p8',
    criticality: 'critical',
    subject: 'Solicitação de adendo contratual: escopo adicional Caldeiraria',
    sender: 'comercial@petrobras.com.br',
    senderName: 'Comercial: Petrobras',
    date: '05/05/2026 09:33',
    group: 'contraparte',
    summary: 'Contraparte solicita formalmente adendo contratual para inclusão de 14 spools de caldeiraria não previstos no escopo original. Indicação de impacto orçamentário de R$ 2,4M.',
    justification: 'Classificado como crítico porque qualquer adendo contratual exige análise jurídica, técnica e orçamentária formal. O e-mail equivale a um gatilho contratual que dispara prazo de resposta de 15 dias úteis (Cláusula 11.2).',
    references: ['Cláusula 11.2: Adendos', 'Anexo I: Lista de spools'],
    starred: true,
    status: 'notificada',
  },
  {
    id: 'p9',
    criticality: 'informative',
    subject: 'Atualização de cronograma físico: semana 18/2026',
    sender: 'plan.boaventura@hc2.com.br',
    senderName: 'Planejamento: HC²',
    date: '04/05/2026 17:55',
    group: 'producao',
    summary: 'Avanço físico semanal: 67,8% acumulado contra previsto de 68,4%. Variação dentro da tolerância contratual de ± 2%.',
    justification: 'Classificado como informativo porque a variação está dentro do limite tolerado pela Cláusula 5.4: Métricas de avanço.',
    references: ['Cláusula 5.4'],
    starred: true,
    status: 'concluida',
  },
  {
    id: 'p10',
    criticality: 'informative',
    subject: 'Reunião de coordenação técnica: ata semanal 18',
    sender: 'eng.coord@hc2.com.br',
    senderName: 'Engenharia: HC²',
    date: '04/05/2026 16:20',
    group: 'engenharia',
    summary: 'Ata da reunião de coordenação técnica da semana 18. Sem deliberações que alterem escopo ou prazo.',
    justification: 'Classificado como informativo. Documento de registro padrão.',
    references: [],
    starred: false,
    status: 'aguardando',
  },
  {
    id: 'p11',
    sharedWithMe: true,
    isUserCreated: true,
    createdByName: 'Carlos Mendes',
    criticality: null,
    pathRisk: null,
    subject: 'Investigação de exposição cambial no aditivo Caldeiraria',
    sender: '',
    senderName: 'Carlos Mendes',
    date: '12/05/2026 10:00',
    group: 'producao',
    summary: 'Investigação iniciada por Carlos Mendes sobre o impacto cambial do aditivo de Caldeiraria nos preços unitários do contrato.',
    justification: '',
    references: [],
    starred: false,
    status: 'em_analise',
  },
];

const SUBCHAT_MESSAGES = {
  p1: [
    {
      role: 'meris',
      time: '09:18',
      content: 'analysis',
    },
  ],
};

const RECIPIENTS_POOL = [
  { id: 'u1', name: 'Ana Paula Ramos', role: 'Gestão Contratual' },
  { id: 'u2', name: 'Carlos Mendes', role: 'Engenharia: Coordenador' },
  { id: 'u3', name: 'Daniela Souza', role: 'Planejamento' },
  { id: 'u4', name: 'Eduardo Lima', role: 'Suprimentos' },
  { id: 'u5', name: 'Fernanda Castro', role: 'Jurídico' },
  { id: 'u6', name: 'Gabriel Tavares', role: 'Qualidade' },
];

const PROJECT_DOCS = [
  { id: 'd1', name: 'Contrato_Boaventura_Rev04.pdf', size: '4,2 MB', type: 'Contrato', when: '12/03/2026' },
  { id: 'd2', name: 'Anexo_I_Lista_Spools.xlsx', size: '380 KB', type: 'Anexo', when: '12/03/2026' },
  { id: 'd3', name: 'Anexo_II_Lista_Reposicao.xlsx', size: '124 KB', type: 'Anexo', when: '12/03/2026' },
  { id: 'd4', name: 'Anexo_III_LMD_RevE.pdf', size: '2,1 MB', type: 'Referência', when: '04/04/2026' },
  { id: 'd5', name: 'Cronograma_Baseline_v3.mpp', size: '720 KB', type: 'Referência', when: '15/03/2026' },
  { id: 'd6', name: 'Matriz_Comunicacao.xlsx', size: '210 KB', type: 'Referência', when: '15/03/2026' },
];

const HISTORY = [
  { when: '07/05/2026 14:22', who: 'Ana Paula Ramos', what: 'Substituiu Anexo_III_LMD_RevD pela Rev. E' },
  { when: '02/05/2026 10:08', who: 'Ana Paula Ramos', what: 'Alterou frequência de resumo: Semanal → Diário' },
  { when: '15/04/2026 09:30', who: 'Carlos Mendes', what: 'Adicionou Cronograma_Baseline_v3.mpp' },
  { when: '12/03/2026 16:50', who: 'Sistema', what: 'Onboarding concluído: 6 documentos carregados' },
];

window.GROUPS = GROUPS;
window.PARECERES = PARECERES;
window.RECIPIENTS_POOL = RECIPIENTS_POOL;
window.PROJECT_DOCS = PROJECT_DOCS;
window.HISTORY = HISTORY;
window.SUBCHAT_MESSAGES = SUBCHAT_MESSAGES;
